LCD Test System
miniat-amos/TeenyAT pull request #6
Opened 2023-12-15 01:14 UTC by NoahBreedy

Base working test system for the TeenyAT

2023-12-16 16:26 UTC, miniat-amos requested changes
There a only a handful of changes / questions that need to be addressed before I can merge.

2023-12-16 16:26 UTC, miniat-amos commented on .gitignore
None of these modifications make sense.  Remove.

2023-12-16 16:26 UTC, miniat-amos commented on docs/ISO.md
While we do need to introduce some of our TeenyAT documentation to the repo, it does not belong in a PR that introduces a new system.

2023-12-16 22:29 UTC, NoahBreedy commented
The thing with the STR >= was not implemented by me. I didn't know
there was an error in regard to range checking.

On Sat, Dec 16, 2023 at 11:26 AM miniat-amos ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> There a only a handful of changes / questions that need to be addressed
> before I can merge.
> ------------------------------
>
> In teenyat.c
> <https://github.com/miniat-amos/TeenyAT/pull/6#discussion_r1428842725>:
>
> > @@ -429,7 +429,7 @@ void tny_clock(teenyat *t) {
>  		}
>  		break;
>  	default:
> -		fprintf(stderr, "Unknown opcode (%d) encountered at 0x%04X on cycle %" PRIu64 "\n",
> +		fprintf(stderr, "Unknown opcode (%d) encountered at 0x%04X on cycle  %" PRIu64 "\n",
>
> Revert this, and be careful when committing in your local repos about
> accidental changes in whitespace.
> ------------------------------
>
> On tnasm/syntax.asm
> <https://github.com/miniat-amos/TeenyAT/pull/6#discussion_r1428842741>:
>
> This file shouldn't have been touched by the addition of the LCD system
> ------------------------------
>
> In tnasm/syntax.asm
> <https://github.com/miniat-amos/TeenyAT/pull/6#discussion_r1428842747>:
>
> > @@ -25,7 +25,7 @@
>  .var age 27
>  .variable count
>
> -;--- Common Instruction formats
> +;--- Common Instruction formats
>
> Revert this, and be careful when committing in your local repos about
> accidental changes in whitespace.
> ------------------------------
>
> In teenyat.c
> <https://github.com/miniat-amos/TeenyAT/pull/6#discussion_r1428844052>:
>
> > @@ -187,7 +187,7 @@ void tny_clock(teenyat *t) {
>  	case TNY_OPCODE_STR:
>  		{
>  			tny_uword addr = t->reg[reg1].s + immed;
> -			if(addr > TNY_MAX_RAM_ADDRESS) {
> +			if(addr >= TNY_MAX_RAM_ADDRESS) {
>
> I remember you'd thought you'd found a range checking error related to the
> top of RAM, but I need a specific example or something to justify this
> change, because I think the change is not correct, but I'm willing to
> believe I could be missing something. TNY_MAX_RAM_ADDRESS is 32767...
> (0x7FFF), and a STR to that address should still be in RAM, correct? Also,
> if there really should be a change here, it should also change everywhere
> (eg, on OPCODE_LOD).
> ------------------------------
>
> On .gitignore
> <https://github.com/miniat-amos/TeenyAT/pull/6#discussion_r1428852921>:
>
> None of these modifications make sense. Remove.
> ------------------------------
>
> On docs/ISO.md
> <https://github.com/miniat-amos/TeenyAT/pull/6#discussion_r1428853198>:
>
> While we do need to introduce some of our TeenyAT documentation to the
> repo, it does not belong in a PR that introduces a new system.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/miniat-amos/TeenyAT/pull/6#pullrequestreview-1785203039>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN2ISXVV2FTFYRQFNNRKC2DYJXDTLAVCNFSM6AAAAABAVW37RKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBVGIYDGMBTHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-19 22:17 UTC, merged

2023-12-19 22:18 UTC, miniat-amos commented
Merged... I restored the last good version of .gitignore, too.