Character dev
miniat-amos/TeenyAT pull request #7
Opened 2023-12-15 01:29 UTC by adevgriff

2023-12-17 05:06 UTC, miniat-amos requested changes

2023-12-17 05:06 UTC, miniat-amos commented on tnasm/parser.cpp
> + * raw_line ::= raw_value.
should still have the + at the end to signify one or more raw_value.

2023-12-17 05:06 UTC, miniat-amos commented on tnasm/parser.cpp
>   * We'll implement the "one-or-more" NUMBER check manually rather than via the
You need to update this comment since you're not using NUMBER any more.

2023-12-17 05:06 UTC, miniat-amos commented on tnasm/test.asm
Should at least have some escaped charaters

2023-12-20 14:06 UTC, adevgriff commented
Bad formatting settings in vs code killed this PR remaking PR on separate branch. This is being done to keep revision history clean.

2023-12-20 14:06 UTC, closed without merging